version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    container_name: fastapi
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level=debug
